-- DEPRECATED: this legacy helper intentionally contains no executable SQL.
-- Earlier versions created public USING (true) policies that allowed anonymous
-- reads and writes to profiles, driver records, jobs, applications and billing.
-- Do not use it. Install in this order instead:
--   1. supabase-schema.sql
--   2. supabase-apnahire-upgrade.sql
--   3. supabase-auth-bootstrap.sql
--   4. supabase-security-hardening.sql
-- The hardened migration scopes data to the authenticated account and hiring
-- participants. Paid candidate-directory search must be implemented through a
-- trusted server-side credit-checking endpoint before enabling directory access.
